apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- import.yaml
configMapGenerator:
- name: openfga-policy-v1
  namespace: sso
  files:
  - store.fga.yaml
generatorOptions:
  disableNameSuffixHash: true
