version: '1alpha4'
rules:
  - id: authentik-users
    match:
      hosts: [{type: exact, value: auth.internal}]
      routes: [{path: /}, {path: /**}]
      scheme: https
    execute:
      - authenticator: session
      - authorizer: service-group
        config:
          values:
            group: sso-users
      - finalizer: noop
    on_error:
      - error_handler: login
        if: >-
          type(Error) == authentication_error &&
          Request.Header("Authorization") == "" &&
          Request.Header("Accept").contains("text/html")
  - id: authentik-admin
    match:
      hosts: [{type: exact, value: authentik.admin.internal}]
      routes: [{path: /}, {path: /**}]
      scheme: https
    execute:
      - authenticator: session
      - authorizer: service-group
        config:
          values:
            group: ""
      - finalizer: noop
    on_error:
      - error_handler: login
        if: >-
          type(Error) == authentication_error &&
          Request.Header("Authorization") == "" &&
          Request.Header("Accept").contains("text/html")
