version: '1alpha4'
rules:
  - id: authentik-users
    match:
      hosts: [{type: exact, value: auth.internal}]
      routes: [{path: /}, {path: /**}]
      scheme: https
    execute:
      - authenticator: session
      - contextualizer: store
      - authorizer: unique-store
      - authorizer: openfga
        config:
          values:
            object: service:auth.internal
      - finalizer: noop
    on_error:
      - error_handler: login
        if: >-
          type(Error) == authentication_error &&
          Request.Header("Authorization") == "" &&
          Request.Header("Accept").contains("text/html")
  - id: authentik-admin
    match:
      hosts: [{type: exact, value: authentik.admin.internal}]
      routes: [{path: /}, {path: /**}]
      scheme: https
    execute:
      - authenticator: session
      - contextualizer: store
      - authorizer: unique-store
      - authorizer: openfga
        config:
          values:
            object: service:authentik.admin.internal
      - finalizer: noop
    on_error:
      - error_handler: login
        if: >-
          type(Error) == authentication_error &&
          Request.Header("Authorization") == "" &&
          Request.Header("Accept").contains("text/html")
  - id: openfga-admin
    match:
      hosts: [{type: exact, value: openfga.admin.internal}]
      routes: [{path: /}, {path: /**}]
      scheme: https
    execute:
      - authenticator: session
      - contextualizer: store
      - authorizer: unique-store
      - authorizer: openfga
        config:
          values:
            object: service:openfga.admin.internal
      - finalizer: openfga-credential
    on_error:
      - error_handler: login
        if: >-
          type(Error) == authentication_error &&
          Request.Header("Authorization") == "" &&
          Request.Header("Accept").contains("text/html")
