apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release.yaml
configMapGenerator:
- name: sso-authentik-blueprints
  namespace: sso
  files:
  - sso.yaml=blueprint.yaml
generatorOptions:
  disableNameSuffixHash: true
